### ISSUE TITLE
Image auto rotate

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#25]
When I upload a vertical format image, it automatically rotate to horizontal format. It should keep it vertical. 
![screen shot 2015-04-14 at 11 04 24 am](https://cloud.githubusercontent.com/assets/7178461/7143786/29b4bf58-e296-11e4-83f0-0781604e110c.png)

**Comment by grahamjleach** [comment]
When you take the picture, your device adds metadata that says it was sideways/landscape. The image data is actually as you see it in this screenshot. When you use a program that is aware of the metadata it may automatically rotate it for you, but for the purposes of the site, I don't think there is anything reasonable that can be done, other than editing the image before upload. Do you think this will be an issue for the cilent?

**Comment by omnitekinc** [comment]
I see, in that case it's fine. thanks!
