### ISSUE TITLE
Submit Test (Message Window) Close button [x]

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#28]
When I click the X to close the window, the test highlight all the wrong ansower and questions I didn't answer, but I can't contiune working on the test, the check box don't work, I have to reload the page to take the test again. 

Expectation, I should be continue to work on the test.

**Comment by grahamjleach** [comment]
Not sure if I understand this functionality. If you could continue to submit, you would be able to just keep submitting until you had all correct answers

**Comment by omnitekinc** [comment]
Yes you should be able to keep submitting until I meet the score requirement. 

But right now if I don't pass, I get the message window, there are 3 options

1. Dashbaord - take me back to dashbaord
2. Retake this test, the page refresh and I have to answer every single questions again
3. Close message window

The problem is when I click close message window, none of the check box or submit button works. So I can't change the wrong answers or submit answers, kind of stuck on this page until I refresh the browser where it wipes out all my answers.
