### ISSUE TITLE
Create New Account, automatically assigned a member ID

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#31]
I created a new single account without member ID but after I save and go back and edit the account, i noticed there is a member ID and when I tried to delete it, I use the delete key on my keyboard, when I hit the key the page reload and took me back to the lesson CMS.

![screen shot 2015-04-17 at 9 21 58 am](https://cloud.githubusercontent.com/assets/7178461/7206141/50adfe2c-e4e3-11e4-8e16-bcf5b710b84b.png)

**Comment by grahamjleach** [comment]
Member ID is a unique key in the database, it can't be changed

**Comment by omnitekinc** [comment]
After checking the member ID, I realised it's not the correct one, I think your memeber ID is something assigned by the system. Where in the old system it's the actually membership ID for AERA, can you please check. 
![screen shot 2015-04-17 at 9 26 00 am](https://cloud.githubusercontent.com/assets/7178461/7216731/89170c38-e5bd-11e4-8586-02055da96fa0.png)
