### ISSUE TITLE
Can't Take Cylinder Exame

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#47]
Even after passing all 1-14, can't take the Cylinder Exame

**Comment by omnitekinc** [comment]
you can use my account, I tested this on the server as well, it doens't work

**Comment by grahamjleach** [comment]
It shows you haven't passed ch 1 or 5...I will complete those and confirm that midterm is available

**Comment by omnitekinc** [comment]
But I have, if you login with my acc stellalai 12345, you will see they are passed.

**Comment by grahamjleach** [comment]
I am using that login

**Comment by omnitekinc** [comment]
are you looking at it on the new server? I am doing my testing on new server with remote desktop.

**Comment by omnitekinc** [comment]
I just check both site I have passed all test. 
![screen shot 2015-04-23 at 5 57 03 pm](https://cloud.githubusercontent.com/assets/7178461/7310527/73539e60-e9e2-11e4-9431-a5419ca04382.png)
![screen shot 2015-04-23 at 5 59 21 pm](https://cloud.githubusercontent.com/assets/7178461/7310531/7e6842d8-e9e2-11e4-8181-6ffb8889a91b.png)
