### ISSUE TITLE
Group Account, Leader is not showing all members

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#49]
This was working before, but now when I checked only you and me are in the group but there are more people
![screen shot 2015-04-25 at 11 53 00 am](https://cloud.githubusercontent.com/assets/7178461/7334192/bcf07eac-eb41-11e4-9688-b265e543f16f.png)

**Comment by grahamjleach** [comment]
I'm able to remove people, if you search AERA now only you and I will show

**Comment by omnitekinc** [comment]
I think you misunderstand the issue. If I login as an admin I see You and me as the AERA Test group. But when I login as Stellalai, I am a group leader, I don't see anyone else, now I can't even see you. I know you removed everyone else but I should still be able to see you under Student. 

![screen shot 2015-04-26 at 12 37 21 pm](https://cloud.githubusercontent.com/assets/7178461/7338933/2377f806-ec11-11e4-85ad-41475808e435.png)
![screen shot 2015-04-26 at 12 37 35 pm](https://cloud.githubusercontent.com/assets/7178461/7338934/237814c6-ec11-11e4-9b49-6980fc6bb755.png)

**Comment by grahamjleach** [comment]
This is probably due to there being 2 AERA Test groups, so this will resolve when I delete the redundant one.
