### ISSUE TITLE
steve fox and amanda potter are not admins

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#50]
Can you make those account admins, I know you did it before but I just tested it just regular accounts

**Comment by grahamjleach** [comment]
done for users "stevefox" and "amandapotter"

**Comment by omnitekinc** [comment]
I just login as stevefox but I don't see accounts on the navigation. I think his account is still regular user, not admin

**Comment by grahamjleach** [comment]
There were 3 users created for "stevefox", deleted the redundant ones, confirmed stevefox has administrator role
