### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#51]
Before I start reuploading the images, I want to make sure there's a easier way to update this instead of having me uploading each image at a time. Because I see it in alot of lessons. 
![screen shot 2015-04-25 at 11 56 38 am](https://cloud.githubusercontent.com/assets/7178461/7334215/2c12d0dc-eb42-11e4-9257-c9b451fb987b.png)

**Comment by grahamjleach** [comment]
realized this needed some different settings for new server, made some updates, this is now working consistently for me

**Comment by omnitekinc** [comment]
I don't think this is working, I tried clear browser history and reload. And there's some strange image of a pizza in this chapter. 
![screen shot 2015-04-26 at 12 33 01 pm](https://cloud.githubusercontent.com/assets/7178461/7338916/6e1e95aa-ec10-11e4-9162-1d041b3caa62.png)

**Comment by omnitekinc** [comment]
Ok something really screwed up, I just tried reupload all the images and even after clearing cache and reload mutiple times I am still see the same thing and the pizza is still there.  

It's Chapter 1, General Safety Guidelines

We need to fix the image issue tonight.

**Comment by omnitekinc** [comment]
Ok something instersting, I embeded the image and it's showing up fine, it just not showing up in the gallery. So probably some weird glitch linking the image.  the image shows you how Fig. 1-10 in the copy is a different image then F. 1-10 in the thumbnail. 

![screen shot 2015-04-26 at 12 56 00 pm](https://cloud.githubusercontent.com/assets/7178461/7338995/c81592a4-ec13-11e4-962a-5f8621397685.png)

**Comment by grahamjleach** [comment]
Please do a full refresh, you need the latest app.js and I believe you have a stale version. This is working.

**Comment by grahamjleach** [comment]
after reloading, then upload the image

**Comment by omnitekinc** [comment]
So I do have to manually reupload all the broken images?

**Comment by grahamjleach** [comment]
There's really no other way to do it. About how many are there? If you have all the images together, you can send them to me and I will replace the broken ones.

**Comment by omnitekinc** [comment]
There are a lot and I have to upload them 1 by 1 and some of these images are huge. I will send them to you by chapter in separate emails.

Thanks!
Stella

**Comment by omnitekinc** [comment]
Ok all missing images have been sent, please let me know once you've updated them and I will go and check.
