### ISSUE TITLE
It's adding extract spacing to the copy

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#52]
It looks like it's still adding extra spaces to the copy, if there's a special character that I can delete in the code to avoid this can you please let me know.

![screen shot 2015-04-25 at 12 01 10 pm](https://cloud.githubusercontent.com/assets/7178461/7334242/d36b0fa2-eb42-11e4-9703-7ff27a2b042a.png)

**Comment by grahamjleach** [comment]
When you copy and paste from a rich editor like word, is pastes a bunch of meta which tinymce deals with. This is where the space (an extra empty p tag) is getting generated. You just have to delete it using the editor.
