### ISSUE TITLE
Can we add a delete account function

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#62]
Client wants to be able to delete user account. I mocked it up and figure it might be easier to just add a text link on the info window. once the admin click on that, a message window show, are you sure you want to delete this account, 2 bottons at the bottom, cancel and delete. 

![screen shot 2015-04-28 at 11 32 10 am](https://cloud.githubusercontent.com/assets/7178461/7377307/66195756-ed9a-11e4-8175-5e6916f5848b.png)

**Comment by grahamjleach** [comment]
done (fyi you will be able to restore accounts and history from database if needed)
