### ISSUE TITLE
Expiration Date is not Correct

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#63]
I just noticed this, when I look at the account over view, this account is already expired in 2014, but when I click on more info, the expiration date say 2016. 
![screen shot 2015-04-28 at 9 54 50 pm](https://cloud.githubusercontent.com/assets/7178461/7384958/5953a272-edf1-11e4-90b5-ff90736835fe.png)
![screen shot 2015-04-28 at 9 54 43 pm](https://cloud.githubusercontent.com/assets/7178461/7384959/5dfaf19a-edf1-11e4-9da4-bad594e3606c.png)

**Comment by grahamjleach** [comment]
I checked in all browsers that I have and I can't recreate this.

**Comment by omnitekinc** [comment]
That's so weird. Anyway, I also tried to change the expiration date so it should be active but I can't login to this account. Can you try?
