### ISSUE TITLE
Expiration Date don't match the Account overview

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#64]
1. The expiration date on the account page are correct
2. Now, just click on an account info, any account and check the expiration date (does it match the one on account page?)
3. I think the first one does.
4. Then click on another account, looks like that same date from the first account is showing up on a different account, so if you click on multiple accounts you will see the same expiration date.
![screen shot 2015-04-30 at 12 42 01 pm](https://cloud.githubusercontent.com/assets/7178461/7421083/9615f994-ef36-11e4-86f9-4428c994b9ad.png)
![screen shot 2015-04-30 at 12 42 12 pm](https://cloud.githubusercontent.com/assets/7178461/7421082/96158d38-ef36-11e4-8f24-7f38c56bd616.png)
![screen shot 2015-04-30 at 12 42 20 pm](https://cloud.githubusercontent.com/assets/7178461/7421081/9614e0f4-ef36-11e4-9450-e55fd10a7e73.png)
![screen shot 2015-04-30 at 12 42 26 pm](https://cloud.githubusercontent.com/assets/7178461/7421084/96176dba-ef36-11e4-9aa3-1fc25323bb22.png)

**Comment by grahamjleach** [comment]
this is fixed
