### ISSUE TITLE
Some user complained about timmer

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#66]
I am not sure if this is even possible but we should check, they got 2 emails from last night saying the test timmer is running at double speed.

**Comment by grahamjleach** [comment]
I can't recreate, but I added a line to prevent more than one timer increment.

**Comment by omnitekinc** [comment]
Another user said that for the final exame, when the timer get to 40 min it stop counting down, can you take a look? 

"I completed the test and there were no strange issues this time and the clock didn't move ahead 3 hrs in 40 minutes.  "

**Comment by grahamjleach** [comment]
I opened the final and let the timer run the full 3 hrs, no issues
